version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net: