apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Memo
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/iusenkanov/store-momo-demo.git
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
