apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-login
      initContainers:
        - name: wait-backend
          image: busybox
          command: ['sh', '-c', 'until nslookup backend; do echo waiting for backend; sleep 2; done']
      containers:
        - name: nginx
          image: ghcr.io/iusenkanov/vue-app:latest
          command: ["/bin/sh", "-c"]
          args: ["nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
              hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32080
